# Generated by Django 6.0.1 on 2026-08-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image_url', models.URLField(blank=True, verbose_name='Image URL')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=500)),
                ('authorization_endpoint', models.URLField()),
                ('token_endpoint', models.URLField()),
                ('userinfo_endpoint', models.URLField()),
                ('jwks_endpoint', models.URLField(blank=True)),
                ('issuer', models.URLField(blank=True)),
                ('scopes', models.CharField(default='openid email profile', max_length=255)),
                ('signing_algorithm', models.CharField(default='RS256', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('authoritative', models.BooleanField(default=False)),
                ('auto_create_users', models.BooleanField(default=True)),
                ('staff_groups_claim', models.CharField(blank=True, default='groups', max_length=100)),
                ('staff_groups', models.CharField(blank=True, default='', help_text='Groups that grant staff access, separated by commas.', max_length=500)),
            ],
            options={
                'verbose_name': 'OIDC provider',
                'verbose_name_plural': 'OIDC providers',
                'ordering': ['name'],
            },
        ),
    ]
