# Generated by Django 6.0.1 on 2026-08-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_oidcidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcidentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='oidcidentity',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='users.oidcprovider', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='oidcidentity',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='oidcidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_identities', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='authoritative',
            field=models.BooleanField(default=False, verbose_name='Authoritative'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='authorization_endpoint',
            field=models.URLField(verbose_name='Authorization endpoint'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='auto_create_users',
            field=models.BooleanField(default=True, verbose_name='Auto-create users'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='client_id',
            field=models.CharField(max_length=255, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='client_secret',
            field=models.CharField(max_length=500, verbose_name='Client secret'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='issuer',
            field=models.URLField(blank=True, verbose_name='Issuer'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='jwks_endpoint',
            field=models.URLField(blank=True, verbose_name='JWKS endpoint'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='scopes',
            field=models.CharField(default='openid email profile', max_length=255, verbose_name='Scopes'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='signing_algorithm',
            field=models.CharField(default='RS256', max_length=20, verbose_name='Signing algorithm'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='staff_groups_claim',
            field=models.CharField(blank=True, default='groups', max_length=100, verbose_name='Staff groups claim'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='token_endpoint',
            field=models.URLField(verbose_name='Token endpoint'),
        ),
        migrations.AlterField(
            model_name='oidcprovider',
            name='userinfo_endpoint',
            field=models.URLField(verbose_name='User info endpoint'),
        ),
    ]
