# Generated by Django 6.0.1 on 2026-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
