# Generated by Django 6.0.1 on 2026-02-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='saturates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipenutrition',
            name='per_serving_saturates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipenutrition',
            name='per_serving_sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipenutrition',
            name='total_saturates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipenutrition',
            name='total_sugar',
            field=models.FloatField(default=0),
        ),
    ]
