# Generated by Django 6.0.1 on 2026-02-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_saturates_ingredient_sugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='generic_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
