# Generated by Django 6.0.1 on 2026-08-01 17:33

import apps.recipes.models.recipe_image
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_unit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={'ordering': ['name'], 'verbose_name': 'Cuisine', 'verbose_name_plural': 'Cuisines'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipeimage',
            options={'verbose_name': 'Recipe Image', 'verbose_name_plural': 'Recipe Images'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['group__order', 'order'], 'verbose_name': 'Recipe Ingredient', 'verbose_name_plural': 'Recipe Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredientgroup',
            options={'ordering': ['order'], 'verbose_name': 'Recipe Ingredient Group', 'verbose_name_plural': 'Recipe Ingredient Groups'},
        ),
        migrations.AlterModelOptions(
            name='recipenote',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'Recipe Note', 'verbose_name_plural': 'Recipe Notes'},
        ),
        migrations.AlterModelOptions(
            name='recipenutrition',
            options={'verbose_name': 'Recipe Nutrition', 'verbose_name_plural': 'Recipe Nutritions'},
        ),
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['order'], 'verbose_name': 'Recipe Step', 'verbose_name_plural': 'Recipe Steps'},
        ),
        migrations.AlterModelOptions(
            name='recipestepgroup',
            options={'ordering': ['order'], 'verbose_name': 'Recipe Step Group', 'verbose_name_plural': 'Recipe Step Groups'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Recipe Tag', 'verbose_name_plural': 'Recipe Tags'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(default=0, verbose_name='Carbs'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='Density'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(default=0, verbose_name='Fat'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='generic_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Generic name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kcal',
            field=models.FloatField(default=0, verbose_name='kcal'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(default=0, verbose_name='Protein'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='salt',
            field=models.FloatField(default=0, verbose_name='Salt'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='saturates',
            field=models.FloatField(default=0, verbose_name='Saturates'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sugar',
            field=models.FloatField(default=0, verbose_name='Sugar'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Cooking time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.cuisine', verbose_name='Cuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Preparation time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='resting_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Resting time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=1, verbose_name='Servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.URLField(blank=True, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to=apps.recipes.models.recipe_image.recipe_image_upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is primary'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipeingredientgroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='recipeingredientgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recipeingredientgroup',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='recipeingredientgroup',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='recipenote',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='recipenote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='recipenote',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='recipenote',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='recipenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='per_serving_carbs',
            field=models.FloatField(default=0, verbose_name='Per serving carbs'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='per_serving_fat',
            field=models.FloatField(default=0, verbose_name='Per serving fat'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='per_serving_kcal',
            field=models.FloatField(default=0, verbose_name='Per serving kcal'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='per_serving_protein',
            field=models.FloatField(default=0, verbose_name='Per serving protein'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='per_serving_salt',
            field=models.FloatField(default=0, verbose_name='Per serving salt'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='per_serving_saturates',
            field=models.FloatField(default=0, verbose_name='Per serving saturates'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='per_serving_sugar',
            field=models.FloatField(default=0, verbose_name='Per serving sugar'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='total_carbs',
            field=models.FloatField(default=0, verbose_name='Total carbs'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='total_fat',
            field=models.FloatField(default=0, verbose_name='Total fat'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='total_kcal',
            field=models.FloatField(default=0, verbose_name='Total kcal'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='total_protein',
            field=models.FloatField(default=0, verbose_name='Total protein'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='total_salt',
            field=models.FloatField(default=0, verbose_name='Total salt'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='total_saturates',
            field=models.FloatField(default=0, verbose_name='Total saturates'),
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='total_sugar',
            field=models.FloatField(default=0, verbose_name='Total sugar'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipestepgroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='recipestepgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recipestepgroup',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='recipestepgroup',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='grams_per_unit',
            field=models.FloatField(blank=True, null=True, verbose_name='Grams per unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ml_per_unit',
            field=models.FloatField(blank=True, null=True, verbose_name='ML per unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
